PROMPT CREATE OR REPLACE TRIGGER tu_cargos
CREATE OR REPLACE TRIGGER tu_cargos
  after update of codigo_unidad_negocio,codigo_tipo_cargo_v,codigo_usuario,codigo_perfil_v,activo
  on cargos
  for each row
 /*
 Creación de trigger para el registro en la bitacora de la estructura CARGOS cuando se modifica un registro
 Requerimiento 378248-Administracion de usuarios
 Ana María Bocanegra Misas
 octubre 2018 */

declare
  -- Declaracion de variables
  VC_CAMPO          TBL_SMT_USUARIO_LOG.CAMPO%TYPE;
  VC_VALOR_ACTUAL   TBL_SMT_USUARIO_LOG.VALOR_ACTUAL%TYPE;
  VC_VALOR_ANTERIOR TBL_SMT_USUARIO_LOG.VALOR_ANTERIOR%TYPE;
  VN_SECUENCIA      NUMBER(10);


begin

-- Asignamos el valor de los campos de acuerdo a las modificaciones realizadas:
-- 1. Modificación en unidad de negocio
IF :OLD.CODIGO_UNIDAD_NEGOCIO <> :NEW.CODIGO_UNIDAD_NEGOCIO THEN

VC_CAMPO          := 'UNIDAD_NEGOCIO';
VC_VALOR_ACTUAL   := :NEW.CODIGO_UNIDAD_NEGOCIO;
VC_VALOR_ANTERIOR := :OLD.CODIGO_UNIDAD_NEGOCIO;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_CARGO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_CARGO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,
EVENTO,CARGO,CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,
'2',:OLD.CODIGO,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el cargo: '||:NEW.CODIGO||'.Campo: ' ||VC_CAMPO);
END IF;

-- 2. Cambio en el tipo de cargo
IF :OLD.CODIGO_TIPO_CARGO_V <> :NEW.CODIGO_TIPO_CARGO_V THEN

VC_CAMPO          := 'TIPO CARGO';
VC_VALOR_ACTUAL   := :NEW.CODIGO_TIPO_CARGO_V;
VC_VALOR_ANTERIOR := :OLD.CODIGO_TIPO_CARGO_V;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_CARGO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_CARGO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,
EVENTO,CARGO,CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,
'2',:OLD.CODIGO,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el cargo: '||:NEW.CODIGO||'.Campo: ' ||VC_CAMPO);
END IF;

-- 3. Cambio en el usuario

IF (:OLD.CODIGO_USUARIO <> :NEW.CODIGO_USUARIO) OR (:OLD.CODIGO_USUARIO IS NULL AND :NEW.CODIGO_USUARIO IS NOT NULL)
OR (:OLD.CODIGO_USUARIO IS NOT NULL AND :NEW.CODIGO_USUARIO IS NULL ) THEN

VC_CAMPO          := 'USUARIO';
VC_VALOR_ACTUAL   := :NEW.CODIGO_USUARIO;
VC_VALOR_ANTERIOR := :OLD.CODIGO_USUARIO;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_CARGO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_CARGO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,
EVENTO,CARGO,CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,'2',
:OLD.CODIGO,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el cargo: '||:NEW.CODIGO||'.Campo: ' ||VC_CAMPO);
END IF;

-- 4. Cambio en el perfil
IF :OLD.CODIGO_PERFIL_V <> :NEW.CODIGO_PERFIL_V THEN

VC_CAMPO          := 'PERFIL';
VC_VALOR_ACTUAL   := :NEW.codigo_perfil_v;
VC_VALOR_ANTERIOR := :OLD.codigo_perfil_v;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_CARGO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_CARGO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,
EVENTO,CARGO,CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,'2',
:OLD.CODIGO,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el cargo: '||:NEW.CODIGO||'.Campo: ' ||VC_CAMPO);
END IF;

-- 4. Cambio en el activo
IF :OLD.ACTIVO <> :NEW.ACTIVO THEN

VC_CAMPO          := 'ESTADO';
VC_VALOR_ACTUAL   := :NEW.ACTIVO;
VC_VALOR_ANTERIOR := :OLD.ACTIVO;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_CARGO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_CARGO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,
EVENTO,CARGO,CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,'2',
:OLD.CODIGO,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el cargo: '||:NEW.CODIGO||'.Campo: ' ||VC_CAMPO);
END IF;

end TU_CARGOS;
/

