PROMPT CREATE OR REPLACE TRIGGER tu_usuario
CREATE OR REPLACE TRIGGER tu_usuario
  after update OF NOMBRE, ACTIVO, DOMINIO_USUARIO ON usuario
  for each row
 /*
 Creación de trigger para el registro en la bitacora de la estructura USUARIO cuando se modifica alguno de sus datos
 Requerimiento 378248-Administracion de usuarios
 Ana María Bocanegra Misas
 octubre 2018
 */
declare
  -- Declaracion de variables
  VC_CAMPO          TBL_SMT_USUARIO_LOG.CAMPO%TYPE;
  VC_VALOR_ACTUAL   TBL_SMT_USUARIO_LOG.VALOR_ACTUAL%TYPE;
  VC_VALOR_ANTERIOR TBL_SMT_USUARIO_LOG.VALOR_ANTERIOR%TYPE;
  VN_SECUENCIA      NUMBER(10);

begin

-- 1. Asignamos el valor de los campos de acuerdo a las modificaciones realizadas:
-- Modificación en nombre de usuario
IF :OLD.NOMBRE <> :NEW.NOMBRE THEN

VC_CAMPO          := 'NOMBRE';
VC_VALOR_ACTUAL   := :NEW.NOMBRE;
VC_VALOR_ANTERIOR := :OLD.NOMBRE;
-- Obtenemos la secuencia de log
SELECT SQ_SMT_USUARIO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_USUARIO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,
EVENTO,USUARIO,CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,'2',
:NEW.CEDULA,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el usuario: '||:NEW.CEDULA||'. Campo: ' ||VC_CAMPO);
END IF;

-- Modificación en activo/inactivo
IF :OLD.ACTIVO <> :NEW.ACTIVO THEN

VC_CAMPO          := 'ESTADO';
VC_VALOR_ACTUAL   := :NEW.ACTIVO;
VC_VALOR_ANTERIOR := :OLD.ACTIVO;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_USUARIO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_USUARIO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,EVENTO,USUARIO,
CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,'2',
:NEW.CEDULA,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el usuario: '||:NEW.CEDULA||'. Campo: ' ||VC_CAMPO);
END IF;

-- Modificación en dominio
IF :OLD.DOMINIO_USUARIO <> :NEW.DOMINIO_USUARIO THEN

VC_CAMPO           := 'DOMINIO';
VC_VALOR_ACTUAL    := :NEW.DOMINIO_USUARIO;
VC_VALOR_ANTERIOR  := :OLD.DOMINIO_USUARIO;

-- Obtenemos la secuencia de log
SELECT SQ_SMT_USUARIO_LOG.NEXTVAL INTO VN_SECUENCIA FROM DUAL;

INSERT INTO TBL_SMT_USUARIO_LOG(ID_SECUENCIA,FECHA_EVENTO,USUARIO_EVENTO,EVENTO,USUARIO,
CAMPO,VALOR_ACTUAL,VALOR_ANTERIOR,DETALLE)
VALUES(VN_SECUENCIA,SYSDATE,:NEW.USUARIO_ACTUALIZACION,'2',
:NEW.CEDULA,VC_CAMPO,VC_VALOR_ACTUAL,VC_VALOR_ANTERIOR,
'Se actualizó el usuario: '||:NEW.CEDULA||'. Campo: ' ||VC_CAMPO);
END IF;

end TU_USUARIO;
/

