PROMPT CREATE OR REPLACE VIEW v_analisis_reporte
CREATE OR REPLACE VIEW v_analisis_reporte (
  id_reporte,
  justificacion_final,
  fecha_acta,
  codigo_estado_reporte_v
) AS
SELECT D.ID_REPORTE,D.JUSTIFICACION_FINAL, D.FECHA_ACTA, D.CODIGO_ESTADO_REPORTE_V FROM DETALLE_ANALISIS_REP D
WHERE (D.ID_REPORTE,D.FECHA_ACTUALIZACION) = (
SELECT ID_REPORTE,MAX(FECHA_ACTUALIZACION) FROM DETALLE_ANALISIS_REP
WHERE ID_REPORTE=D.ID_REPORTE
GROUP BY ID_REPORTE
)
/

