PROMPT CREATE OR REPLACE VIEW v_clientes_filtro_estado
CREATE OR REPLACE VIEW v_clientes_filtro_estado (
  id,
  tipo_identificacion,
  numero_identificacion,
  codigo_cargo,
  codigo_unidad_negocio,
  codigo_producto,
  fecha_creacion,
  numero_negocio,
  region,
  zona,
  estado,
  descripcion_estado
) AS
SELECT F.ID,F.TIPO_IDENTIFICACION,F.NUMERO_IDENTIFICACION,
F.CODIGO_CARGO,C.CODIGO_UNIDAD_NEGOCIO,F.CODIGO_PRODUCTO,F.FECHA_CREACION,
F.NUMERO_NEGOCIO,U.CODIGO_REGION_V REGION,U.CODIGO_ZONA ZONA,F.ESTADO_FILTRO ESTADO,
DECODE(F.ESTADO_FILTRO,'0','Pendiente','1','Aprobado','2','Inactivo','3','Rechazado')DESCRIPCION_ESTADO
FROM FILTROS F,CARGOS C,UNIDADES_NEGOCIO U
WHERE
C.CODIGO = F.CODIGO_CARGO
AND U.CODIGO = C.CODIGO_UNIDAD_NEGOCIO
AND F.ID IN(
SELECT MAX(ID) FROM FILTROS F1
WHERE F1.CODIGO_CARGO= F.CODIGO_CARGO AND
F1.TIPO_IDENTIFICACION=F.TIPO_IDENTIFICACION
AND F1.NUMERO_IDENTIFICACION= F.NUMERO_IDENTIFICACION
AND F1.CODIGO_PRODUCTO= F.CODIGO_PRODUCTO
AND F1.NUMERO_NEGOCIO= F.NUMERO_NEGOCIO
GROUP BY TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION,CODIGO_PRODUCTO, NUMERO_NEGOCIO, CODIGO_CARGO)
ORDER BY TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION,NUMERO_NEGOCIO
/

