PROMPT CREATE OR REPLACE VIEW v_filtro_activo
CREATE OR REPLACE VIEW v_filtro_activo (
  tipo_identificacion,
  numero_identificacion,
  codigo_cargo,
  codigo_unidad_negocio,
  codigo_region,
  activo
) AS
SELECT
TIPO_IDENTIFICACION,
NUMERO_IDENTIFICACION,
CODIGO_CARGO,
CODIGO_UNIDAD_NEGOCIO,
CODIGO_REGION_V CODIGO_REGION,
1 ACTIVO
FROM
FILTROS,
CARGOS,
UNIDADES_NEGOCIO
WHERE
CARGOS.CODIGO = FILTROS.CODIGO_CARGO AND
SYSDATE BETWEEN VIGENTE_DESDE AND Nvl(VIGENTE_HASTA, '2025/12/31') AND
UNIDADES_NEGOCIO.CODIGO = CARGOS.CODIGO_UNIDAD_NEGOCIO
UNION
SELECT
TIPO_IDENTIFICACION,
NUMERO_IDENTIFICACION,
CODIGO_CARGO,
CODIGO_UNIDAD_NEGOCIO,
CODIGO_REGION_V CODIGO_REGION,
0 ACTIVO
FROM
FILTROS F,
CARGOS,
UNIDADES_NEGOCIO
WHERE
CARGOS.CODIGO = F.CODIGO_CARGO AND
NOT EXISTS(
SELECT
1
FROM
FILTROS F1
WHERE
SYSDATE BETWEEN F1.VIGENTE_DESDE AND Nvl(F1.VIGENTE_HASTA, '2025/12/31')
AND F1.TIPO_IDENTIFICACION = F.TIPO_IDENTIFICACION
AND F1.NUMERO_IDENTIFICACION = F.NUMERO_IDENTIFICACION
AND F1.CODIGO_CARGO = F.CODIGO_CARGO
)
AND UNIDADES_NEGOCIO.CODIGO = CARGOS.CODIGO_UNIDAD_NEGOCIO
/

