PROMPT CREATE OR REPLACE VIEW v_lista_valores_admin
CREATE OR REPLACE VIEW v_lista_valores_admin (
  tipo_dato,
  descripcion_tipo_dato,
  codigo,
  nombre_corto,
  nombre_largo,
  activo,
  aplica_gerente,
  usuario_actualizacion,
  fecha_actualizacion
) AS
SELECT
TIPO_DATO TIPO_DATO,
DECODE(TIPO_DATO,
1, 'TIPOS DE ARCHIVO',
2, 'PRODUCTOS',
3, 'REGION',
4, 'TIPOS DE REPORTE',
5,'OPERADORES LOGICOS',
6, 'MONEDAS',
7, 'CLASES REPORTE',
8, 'TIPOS DE CONSULTA',
9, 'ESTADOS REPORTE',
10, 'PERFILES',
11, 'ESTADOS_TRANSACCION',
12, 'TIPOS RELACION CON EL BANCO',
13, 'RAZONES RETIRO',
14, 'TIPOS DE CARGO',
15, 'TIPOS DE LISTA',
16, 'TIPOS DE MOTIVOS',
17, 'TIPOS DE DOCUMENTO',
18, 'TIPOS DE DIRECCION',
19, 'TIPOS DE DATOS',
20, 'PROCESOS',
21, 'TIPOS DE EMPRESA',
22, 'TIPOS DE TELEFONO',
23, 'RUTAS BASE DATOS',
24, 'TIPOS DE ENTIDADES',
26, 'DEPURACION'
) DESCRIPCION_TIPO_DATO,
CODIGO CODIGO,
NOMBRE_CORTO NOMBRE_CORTO,
NOMBRE_LARGO NOMBRE_LARGO,
LISTA_VALORES.ACTIVO,
APLICA_GERENTE,
USUARIO.NOMBRE USUARIO_ACTUALIZACION,
LISTA_VALORES.FECHA_ACTUALIZACION
FROM LISTA_VALORES,
USUARIO
WHERE USUARIO.CEDULA(+) = LISTA_VALORES.USUARIO_ACTUALIZACION
ORDER BY TIPO_DATO, CODIGO
/

