PROMPT CREATE OR REPLACE VIEW v_listas_cruce
CREATE OR REPLACE VIEW v_listas_cruce (
  codigo_motivo_v,
  nombre_motivo,
  tipo_identificacion,
  numero_identificacion,
  apellidos_razon_social,
  nombres_razon_comercial,
  alias,
  tipo_reporte,
  ros,
  comentario,
  fecha_ingreso,
  id_reporte
) AS
SELECT CODIGO_MOTIVO_V,
M.NOMBRE_LARGO NOMBRE_MOTIVO,
P.TIPO_IDENTIFICACION TIPO_IDENTIFICACION,
P.NUMERO_IDENTIFICACION NUMERO_IDENTIFICACION,
P.APELLIDOS_RAZON_SOCIAL APELLIDOS_RAZON_SOCIAL,
P.NOMBRES_RAZON_COMERCIAL NOMBRES_RAZON_COMERCIAL,
ALIAS,
CASE WHEN ID_REPORTE IS NULL THEN TIPO_REPORTE ELSE R.CODIGO_TIPO_REPORTE_V END TIPO_REPORTE,
CASE WHEN ID_REPORTE IS NULL THEN ROS ELSE TO_CHAR(R.ROS_RELACIONADO) END ROS,
comentario,
fecha_ingreso,
ID_REPORTE
FROM PERSONAS_REPORTADAS P,
LISTA_VALORES M,
REPORTE R
WHERE
M.TIPO_DATO = '16' AND
M.CODIGO = CODIGO_MOTIVO_V AND
R.ID(+) = ID_REPORTE
/

