PROMPT CREATE OR REPLACE VIEW v_menu
CREATE OR REPLACE VIEW v_menu (
  orden,
  title,
  pagina,
  class,
  nombre_opcion,
  perfil
) AS
SELECT OPCIONES_MENU.CODIGO, OPCIONES_MENU.DESCRIPCION, OPCIONES_MENU.PAGINA, OPCIONES_MENU.CLASS, OPCIONES_MENU.OPCION, PERFILES_MENU.CODIGO_PERFIL_V
       FROM PERFILES_MENU, OPCIONES_MENU
       WHERE PERFILES_MENU.CODIGO_OPCION_MENU = OPCIONES_MENU.CODIGO
/

