PROMPT CREATE OR REPLACE VIEW v_operadores_logicos
CREATE OR REPLACE VIEW v_operadores_logicos (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO = 5
/

