PROMPT CREATE OR REPLACE VIEW v_perfiles
CREATE OR REPLACE VIEW v_perfiles (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO = 10
/

