PROMPT CREATE OR REPLACE VIEW v_productos
CREATE OR REPLACE VIEW v_productos (
  codigo,
  desc_corta,
  desc_larga
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_CORTO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO=2
/

