PROMPT CREATE OR REPLACE VIEW v_preguntas
CREATE OR REPLACE VIEW v_preguntas (
  tipo_pregunta,
  descripcion_tipo_pregunta,
  id_pregunta,
  vigente_desde,
  vigente_hasta,
  pregunta,
  fecha_actualizacion,
  usuario_actualizacion
) AS
select
TIPO_PREGUNTA_V TIPO_PREGUNTA,
DECODE(TIPO_PREGUNTA_V,
'A', 'FUENTES INFORMACIÓN BOOLEAN',
'N', 'CONOCIMIENTO CLIENTE BOOLEAN',
'R', 'DOCUMENTOS SOPORTE TEXT',
'S', 'DOCUMENTOS SOPORTE BOOLEAN'
) DESCRIPCION_TIPO_PREGUNTA,
ID ID_PREGUNTA,
VIGENTE_DESDE,
VIGENTE_HASTA,
DESCRIPCION PREGUNTA,
PREGUNTAS_REP.FECHA_ACTUALIZACION,
USUARIO.NOMBRE USUARIO_ACTUALIZACION
FROM PREGUNTAS_REP,
USUARIO
WHERE
USUARIO.CEDULA(+) = PREGUNTAS_REP.USUARIO_ACTUALIZACION
/

