PROMPT CREATE OR REPLACE VIEW v_razones_retiro
CREATE OR REPLACE VIEW v_razones_retiro (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO = 13
/

