PROMPT CREATE OR REPLACE VIEW v_relacion_reportes
CREATE OR REPLACE VIEW v_relacion_reportes (
  id_reporte,
  ros,
  region,
  zona,
  oficina,
  fecha_creacion,
  usuario,
  codigo_perfil,
  perfil,
  estado,
  codigo_estado,
  codigo_cargo,
  codigo_region,
  codigo_zona,
  codigo_oficina,
  numero_identificacion,
  tipo_identificacion,
  codigo_clase,
  clase_reporte
) AS
SELECT
R.ID ID_REPORTE,
R.ROS_RELACIONADO ROS,
REG.NOMBRE_CORTO REGION,
Z.NOMBRE_CORTO ZONA,
U.DESCRIPCION OFICINA,
R.FECHA_CREACION,
US.NOMBRE USUARIO,
P.CODIGO CODIGO_PERFIL,
P.NOMBRE_LARGO PERFIL,
E.NOMBRE_LARGO ESTADO,
E.CODIGO CODIGO_ESTADO,
R.CODIGO_CARGO,
REG.CODIGO CODIGO_REGION,
Z.CODIGO CODIGO_ZONA,
U.CODIGO CODIGO_OFICINA,
R.NUMERO_IDENTIFICACION,
R.TIPO_IDENTIFICACION,
R.CODIGO_CLASE_REPORTE_V CODIGO_CLASE,
CLASE.NOMBRE_LARGO CLASE_REPORTE
FROM REPORTE R,
CARGOS C,
UNIDADES_NEGOCIO U,
ZONAS Z,
LISTA_VALORES REG,
LISTA_VALORES E,
USUARIO US,
LISTA_VALORES P,
LISTA_VALORES CLASE
WHERE
C.CODIGO = R.CODIGO_CARGO AND
U.CODIGO = C.CODIGO_UNIDAD_NEGOCIO AND
Z.CODIGO(+) = U.CODIGO_ZONA AND
Z.CODIGO_REGION_V(+) = U.CODIGO_REGION_V AND
REG.CODIGO(+) =Z.CODIGO_REGION_V AND
REG.TIPO_DATO(+)=3 AND
E.CODIGO = R.CODIGO_ESTADO_REPORTE_V AND
E.TIPO_DATO=9 AND
US.CEDULA = R.USUARIO_CREACION AND
P.CODIGO(+) = C.CODIGO_PERFIL_V AND
P.TIPO_DATO (+)= 10  AND
CLASE.TIPO_DATO = 7 AND
CLASE.CODIGO = R.CODIGO_CLASE_REPORTE_V
/

