PROMPT CREATE OR REPLACE VIEW v_region
CREATE OR REPLACE VIEW v_region (
  codigo,
  desc_corta,
  desc_larga,
  activo
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_CORTO, LISTA_VALORES.NOMBRE_LARGO,ACTIVO
FROM LISTA_VALORES
WHERE TIPO_DATO=3
/

