PROMPT CREATE OR REPLACE VIEW v_rutas_bd
CREATE OR REPLACE VIEW v_rutas_bd (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
FROM LISTA_VALORES
WHERE TIPO_DATO = 23
/

