PROMPT CREATE OR REPLACE VIEW v_tipos_empresa
CREATE OR REPLACE VIEW v_tipos_empresa (
  codigo,
  nombre_largo
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
FROM LISTA_VALORES
WHERE TIPO_DATO = 21
/

