PROMPT CREATE OR REPLACE VIEW v_tipo_archivo
CREATE OR REPLACE VIEW v_tipo_archivo (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO = 1
/

