PROMPT CREATE OR REPLACE VIEW v_tipo_cargo
CREATE OR REPLACE VIEW v_tipo_cargo (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO = 14
/

