PROMPT CREATE OR REPLACE VIEW v_tipos_direccion
CREATE OR REPLACE VIEW v_tipos_direccion (
  codigo,
  nombre_largo
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
FROM LISTA_VALORES
WHERE TIPO_DATO = 18
/

