PROMPT CREATE OR REPLACE VIEW v_tipos_reporte
CREATE OR REPLACE VIEW v_tipos_reporte (
  codigo,
  descripcion
) AS
SELECT LISTA_VALORES.CODIGO, LISTA_VALORES.NOMBRE_LARGO
       FROM LISTA_VALORES
       WHERE TIPO_DATO = 4
/

