PROMPT CREATE OR REPLACE VIEW v_tr_preinusuales
CREATE OR REPLACE VIEW v_tr_preinusuales (
  fecha,
  codigo_fuente,
  fuente,
  estado_oficina,
  estado_ducc,
  mayor_riesgo,
  nueva,
  nc_region,
  region,
  nc_zona,
  zona,
  codigo_oficina,
  oficina
) AS
select fecha_proceso FECHA,
VP.codigo CODIGO_FUENTE,
VP.NOMBRE_CORTO FUENTE,
VE1.NOMBRE_CORTO estado_oficina,
VE2.NOMBRE_CORTO estado_ducc,
TC.MAYOR_RIESGO,
nueva,
VR.NOMBRE_CORTO NC_REGION,
VR.CODIGO REGION,
Z.NOMBRE_CORTO NC_ZONA,
Z.CODIGO ZONA,
CODIGO_OFICINA CODIGO_OFICINA,
UN.DESCRIPCION OFICINA
FROM TRANSACCIONES_CLIENTE TC,
UNIDADES_NEGOCIO UN,
ZONAS Z,
LISTA_VALORES VR,
LISTA_VALORES VE1,
LISTA_VALORES VE2,
LISTA_VALORES VP,
TIPOS_TRANSACCION TT,
archivos AR
WHERE
UN.CODIGO = TC.CODIGO_OFICINA AND
VR.CODIGO(+) = UN.CODIGO_REGION_V AND
VR.TIPO_DATO = 3 AND
Z.CODIGO_REGION_V(+) = UN.CODIGO_REGION_V AND
Z.CODIGO(+) = UN.CODIGO_ZONA AND
VE1.TIPO_DATO = 11 AND
VE1.CODIGO = TC.ESTADO_OFICINA AND
VE2.TIPO_DATO = 11 AND
VE2.CODIGO = TC.ESTADO_DUCC AND
VP.TIPO_DATO = 2  AND
VP.CODIGO = ar.codigo_producto_v AND
TT.CODIGO_TRANSACCION = TC.CODIGO_TRANSACCION AND
TT.CODIGO_PRODUCTO_V = AR.CODIGO_PRODUCTO_V AND
ar.codigo = tc.codigo_archivo
/

