PROMPT CREATE OR REPLACE VIEW v_un
CREATE OR REPLACE VIEW v_un (
  codigo_unidad_negocio,
  nombre_unidad_negocio,
  codigo_zona,
  nombre_zona,
  codigo_region_v,
  nombre_region,
  activa,
  ceo,
  plaza_critica,
  is_megabanco
) AS
SELECT
U.CODIGO CODIGO_UNIDAD_NEGOCIO,
U.DESCRIPCION nombre_UNIDAD_NEGOCIO ,
Z.CODIGO CODIGO_ZONA,
Z.NOMBRE_LARGO NOMBRE_ZONA,
R.CODIGO CODIGO_REGION_V,
R.NOMBRE_LARGO NOMBRE_REGION,
U.ACTIVA,
U.CEO,
U.PLAZA_CRITICA,
U.IS_MEGABANCO
FROM
UNIDADES_NEGOCIO U,
ZONAS Z,
LISTA_VALORES R
WHERE
R.TIPO_DATO = 3 AND
R.CODIGO = U.CODIGO_REGION_V AND
Z.CODIGO(+) = U.CODIGO_ZONA AND
Z.CODIGO_REGION_V(+) = U.CODIGO_REGION_V
/

