PROMPT CREATE OR REPLACE VIEW v_usuarios
CREATE OR REPLACE VIEW v_usuarios (
  codigo_usuario,
  nombre_usuario,
  codigo_cargo,
  nombre_tipo_cargo,
  usuario_activo,
  cargo_activo,
  dominio_usuario,
  codigo_tipo_cargo,
  codigo_perfil,
  nombre_perfil,
  codigo_unidad_negocio,
  nombre_unidad_negocio,
  nombre_zona,
  codigo_zona,
  nombre_corto_zona,
  nombre_region,
  codigo_region,
  nombre_corto_region,
  ceo,
  is_megabanco
) AS
SELECT
CEDULA "CODIGO_USUARIO",
NOMBRE "NOMBRE_USUARIO",
C.CODIGO "CODIGO_CARGO",
TC.DESCRIPCION "NOMBRE_TIPO_CARGO",
USUARIO.ACTIVO "USUARIO_ACTIVO",
C.ACTIVO "CARGO_ACTIVO",
DOMINIO_USUARIO "DOMINIO_USUARIO",
CODIGO_TIPO_CARGO_V "CODIGO_TIPO_CARGO",
CODIGO_PERFIL_V "CODIGO_PERFIL",
PF.DESCRIPCION "NOMBRE_PERFIL",
CODIGO_UNIDAD_NEGOCIO "CODIGO_UNIDAD_NEGOCIO",
U.DESCRIPCION "NOMBRE_UNIDAD_NEGOCIO",
Z.NOMBRE_LARGO "NOMBRE_ZONA",
Z.CODIGO "CODIGO_ZONA",
Z.NOMBRE_CORTO "NOMBRE_CORTO_ZONA",
VR.DESC_LARGA "NOMBRE_REGION",
VR.CODIGO "CODIGO_REGION",
VR.DESC_CORTA "NOMBRE_CORTO_REGION",
U.CEO CEO,
U.IS_MEGABANCO IS_MEGABANCO
FROM
USUARIO,
CARGOS C,
V_TIPO_CARGO TC,
V_PERFILES PF,
UNIDADES_NEGOCIO U,
ZONAS Z,
V_REGION VR
WHERE C.CODIGO_USUARIO = USUARIO.CEDULA(+)
AND U.CODIGO = C.CODIGO_UNIDAD_NEGOCIO
AND Z.CODIGO(+) = U.CODIGO_ZONA
AND Z.CODIGO_REGION_V(+) = U.CODIGO_REGION_V
AND VR.CODIGO(+) = U.CODIGO_REGION_V
AND C.CODIGO_TIPO_CARGO_V = TC.CODIGO
AND C.CODIGO_PERFIL_V = PF.CODIGO
/

